package com.dots.games.pratick.dots.Enums;

/**
 * Created by Pratick on 05-06-2015.
 *
 */
public enum ACHIEVEMENT_TYPE
{
    START,FINISH,WIN,DRAW,LOSE,SPECTATOR,

    SINGLE_PLAYER_START,MULTI_PLAYER_START,MIXED_PLAYER_START,
    SINGLE_PLAYER_FINISH,MULTI_PLAYER_FINISH,MIXED_PLAYER_FINISH,
    SINGLE_PLAYER_WIN,MULTI_PLAYER_WIN,MIXED_PLAYER_WIN,
    SINGLE_PLAYER_DRAW,MULTI_PLAYER_DRAW,MIXED_PLAYER_DRAW,
    SINGLE_PLAYER_LOSE,MULTI_PLAYER_LOSE,MIXED_PLAYER_LOSE,
}
